### ISSUE TITLE
The npm package includes a large file testling.html

### ISSUE THREAD

**Issue by yanxyz** [ljharb/is-generator-function#13]
![image](https://user-images.githubusercontent.com/737120/31371710-f3b246da-adc4-11e7-9558-55e146c2e588.png)

This file and some other files could be ignored in the npm package .

**Comment by ljharb** [comment]
Indeed; testling.html can be npmignored, as maybe could the Makefile. Every other file, however, needs to be there.

**Comment by ljharb** [comment]
This was already covered in f71e5dc4abb957f4632418bf7d56f636bbe2e3da / #8; it just hasn't been released to npm yet.
