### ISSUE TITLE
Why is the Makefile so complex?

### ISSUE THREAD

**Issue by bucaran** [ljharb/is-generator-function#3]
Do you have a fetiche for complexity or is there a reason I am missing about why is the Makefile so complex? Why not using npm scripts, a simple `.sh` script or a Brocoli salad?

Cheers! :smile:

**Comment by ljharb** [comment]
The Makefile is for `make release`. `npm scripts` are great, and both `make` and `npm` is a better and simpler approach than anything else.

This is a standard Makefile I use across many projects.
