### ISSUE TITLE
Any idea on how to use it with babel?

### ISSUE THREAD

**Issue by kilianc** [ljharb/is-generator-function#4]
The generator is always transpiled to plain function so... it is impossible to know

**Comment by kilianc** [comment]
https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=true&code=function%20*%20foo%20()%20%7B%0A%7D

**Comment by ljharb** [comment]
generators can't be transpiled/shimmed. babel uses `regenerator`, which my module does not consider to be a proper generator.

You can use https://www.npmjs.com/package/is-generator if you need to check for fake generators - I believe that will work for regenerator functions.
